name: "Oxypals Podcast Generator"
author: "Maksym Chernomaz"
description: "Generates fedd from YAML"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    desciption: "Email"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Name"
    required: true
    default: ${{ github.actor }}
